### ISSUE TITLE
Add GitHub Pages Example Deployment

### ISSUE THREAD

**Issue by curran** [curran/vite-d3-template#15]
As a user who exported things out of VizHub, I want to use GitHub Pages to automate the deployment of my Vite app.

**Comment by curran** [comment]
```
image: node:16.5.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
```

from https://vitejs.dev/guide/static-deploy
